### ISSUE TITLE
Model baking not working when table contains _ 

### ISSUE THREAD

**Issue by daniel-lang** [cakephp/bake#132]
I have a table in the database that is called `group_members`. When I run `bin/cake bake model` it returns the list of available models. This list contains the option `GroupMembers` but when I call `bin/cake bake model GroupsMembers` it is unable to find the table.

Full Error:
```
Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'prayerscloud.groupmembers' doesn't exist in [/vagrant/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 130]
2015-07-04 12:46:44 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'prayerscloud.groupmembers' doesn't exist
Stack Trace:
#0 /vagrant/vendor/cakephp/cakephp/src/Database/Schema/Collection.php(96): Cake\Database\Schema\Collection->_reflect('Column', 'groupmembers', Array, Object(Cake\Database\Schema\Table))
#1 /vagrant/vendor/cakephp/cakephp/src/Database/Schema/CachedCollection.php(65): Cake\Database\Schema\Collection->describe('groupmembers', Array)
#2 /vagrant/vendor/cakephp/cakephp/src/ORM/Table.php(426): Cake\Database\Schema\CachedCollection->describe('groupmembers')
#3 /vagrant/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(244): Cake\ORM\Table->schema()
#4 /vagrant/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(196): Bake\Shell\Task\ModelTask->findBelongsTo(Object(App\Model\Table\GroupmembersTable), Array)
#5 /vagrant/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(110): Bake\Shell\Task\ModelTask->getAssociations(Object(App\Model\Table\GroupmembersTable))
#6 /vagrant/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(96): Bake\Shell\Task\ModelTask->bake('GroupMembers')
#7 [internal function]: Bake\Shell\Task\ModelTask->main('GroupMembers')
#8 /vagrant/vendor/cakephp/cakephp/src/Console/Shell.php(391): call_user_func_array(Array, Array)
#9 /vagrant/vendor/cakephp/cakephp/src/Console/Shell.php(386): Cake\Console\Shell->runCommand(Array, false)
#10 /vagrant/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(204): Cake\Console\Shell->runCommand(Array, true)
#11 /vagrant/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(175): Cake\Console\ShellDispatcher->_dispatch()
#12 /vagrant/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch()
#13 /vagrant/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#14 {main}
```

**Comment by daniel-lang** [comment]
I downgraded to 1.0.9 and upgraded and again and now it works. Very interesting...
