### ISSUE TITLE
Cake 3.x bake all return a syntax error in MysqlStatement.php

### ISSUE THREAD

**Issue by Kareylo** [cakephp/bake#258]
This is a (multiple allowed):

- [X] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.2.11 (latest stable via composer)
- Platform and Targe: Windows 10/WAMP/Apache/Mysql

## What you did

Just after creating a simple database, I tried to make a complete bake with
```bash
bin/cake bake all
```

## Expected Behavior

Got a complete code generated with bake

## Actual Behavior

Got an error from Bake and MysqlStatement, so I don't have any code generated
```bash
Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 Erreur de syntaxe pr├¿s de '.`dev`' ├á la ligne 1 in [E:\wamp\www\test\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php, line 36]
2016-07-05 16:30:50 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 Erreur de syntaxe pr├¿s de '.`dev`' ├á la ligne 1
Stack Trace:
#0 E:\wamp\www\test\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 E:\wamp\www\test\vendor\cakephp\cakephp\src\Database\Connection.php(286): Cake\Database\Statement\MysqlStatement->execute()
#2 E:\wamp\www\test\vendor\cakephp\cakephp\src\Database\Connection.php(243): Cake\Database\Connection->query('SHOW TABLES FRO...')
#3 E:\wamp\www\test\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(64): Cake\Database\Connection->execute('SHOW TABLES FRO...', Array)
#4 E:\wamp\www\test\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(921): Cake\Database\Schema\Collection->listTables()
#5 E:\wamp\www\test\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(875): Bake\Shell\Task\ModelTask->_getAllTables()
#6 E:\wamp\www\test\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(198): Bake\Shell\Task\ModelTask->listAll()
#7 E:\wamp\www\test\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(124): Bake\Shell\Task\ModelTask->getAssociations(Object(Cake\ORM\Table))
#8 E:\wamp\www\test\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(109): Bake\Shell\Task\ModelTask->getTableContext(Object(Cake\ORM\Table), 'posts', 'Posts')
#9 E:\wamp\www\test\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(96): Bake\Shell\Task\ModelTask->bake('Posts')
#10 E:\wamp\www\test\vendor\cakephp\bake\src\Shell\BakeShell.php(250): Bake\Shell\Task\ModelTask->main('Posts')
#11 E:\wamp\www\test\vendor\cakephp\cakephp\src\Collection\CollectionTrait.php(51): Bake\Shell\BakeShell->Bake\Shell\{closure}('Posts', 0)
#12 E:\wamp\www\test\vendor\cakephp\bake\src\Shell\BakeShell.php(253): Cake\Collection\Collection->each(Object(Closure))
#13 [internal function]: Bake\Shell\BakeShell->all('posts')
#14 E:\wamp\www\test\vendor\cakephp\cakephp\src\Console\Shell.php(444): call_user_func_array(Array, Array)
#15 E:\wamp\www\test\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(221): Cake\Console\Shell->runCommand(Array, true, Array)
#16 E:\wamp\www\test\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(181): Cake\Console\ShellDispatcher->_dispatch(Array)
#17 E:\wamp\www\test\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(127): Cake\Console\ShellDispatcher->dispatch(Array)
#18 E:\wamp\www\test\bin\cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#19 {main}
```

And there the SQL code to create the table I try to convert

```sql
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `kareylo.dev` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `kareylo.dev`;
CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `content` longtext NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `posts_tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` int(10) unsigned NOT NULL,
  `tag_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `post_id` (`post_id`),
  KEY `tag_id` (`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
```

**Comment by ADmad** [comment]
Database names with dot in them are not supported. Use another name.
