### ISSUE TITLE
Can't create Seed with bake command line

### ISSUE THREAD

**Issue by EdouardTack** [cakephp/bake#353]
Hi,
This is my configuration (update today):
* php 7.0.10
* cakephp 3.3.16

When I use this command line ` php bin/cake.php bake seed UserGroups`. I've this error
```
Exception: Call to a member function set() on null in [\vendor\cakephp\bake\src\Shell\Task\SimpleBakeTask.php, line 100]
2017-08-02 14:22:26 Error: [Error] Call to a member function set() on null
Stack Trace:
#0 \vendor\cakephp\migrations\src\Shell\Task\SeedTask.php(132): Bake\Shell\Task\SimpleBakeTask->bake('UserGroups')
#1 \vendor\cakephp\bake\src\Shell\Task\SimpleBakeTask.php(87): Migrations\Shell\Task\SeedTask->bake('UserGroups')
#2 [internal function]: Bake\Shell\Task\SimpleBakeTask->main('UserGroups')
#3 \vendor\cakephp\cakephp\src\Console\Shell.php(472): call_user_func_array(Array, Array)
#4 \vendor\cakephp\cakephp\src\Console\Shell.php(465): Cake\Console\Shell->runCommand(Array, false, Array)
#5 \vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(227): Cake\Console\Shell->runCommand(Array, true, Array)
#6 \vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#7 \vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#8 \bin\cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#9 {main}
```

This is the line [SimpleBakeTask.php#L98](https://github.com/cakephp/bake/blob/master/src/Shell/Task/SimpleBakeTask.php#L98), my property `$this->BakeTemplate` is null

I try the other command from bake, all is good.

**Comment by HavokInspiration** [comment]
I can take a look and see if I can reproduce.

**Comment by HavokInspiration** [comment]
I opened a pull request on the migrations repo : https://github.com/cakephp/migrations/issues/322

Thanks for reporting @EdouardTack !
