### ISSUE TITLE
Missing Twig_SourceContextLoaderInterface implementation

### ISSUE THREAD

**Issue by hraq** [cakephp/bake#413]
While trying to bake new model/seed etc, bake throws an error for missing implementation.

CakePHP: 3.5.4
PHP: 7.0.18 (win)

When switching cakephp/bake to 1.4.* I can bake. But not any prior versions.
On project, cakephp/bake is only place were Twig is used.

```
$ bin/cake bake model MyModel
One moment while associations are detected.
Exception: Twig loader "WyriHaximus\TwigView\Lib\Twig\Loader" should implement Twig_SourceContextLoaderInterface since version 1.27. in C:\path\to\project\vendor\twig\twig\lib\Twig\Environment.php:782. in [C:\path\to\project\vendor\twig\twig\lib\Twig\Environment.php, line 782]
2018-01-30 10:18:16 Error: [ErrorException] Twig loader "WyriHaximus\TwigView\Lib\Twig\Loader" should implement Twig_SourceContextLoaderInterface since version 1.27. in C:\path\to\project\vendor\twig\twig\lib\Twig\Environment.php:782. in C:\path\to\project\vendor\twig\twig\lib\Twig\Environment.php on line 782
Stack Trace:
#0 [internal function]: App\Console\ConsoleErrorHandler->handleError(16384, 'Twig loader "Wy...', 'C:\\path\\to...', 782, Array)
#1 C:\path\to\project\vendor\twig\twig\lib\Twig\Environment.php(782): trigger_error('Twig loader "Wy...', 16384)
#2 C:\path\to\project\vendor\twig\twig\lib\Twig\Environment.php(104): Twig_Environment->setLoader(Object(WyriHaximus\TwigView\Lib\Twig\Loader))
#3 C:\path\to\project\vendor\wyrihaximus\twig-view\src\View\TwigView.php(67): Twig_Environment->__construct(Object(WyriHaximus\TwigView\Lib\Twig\Loader), Array)
#4 C:\path\to\project\vendor\cakephp\bake\src\View\BakeView.php(104): WyriHaximus\TwigView\View\TwigView->initialize()
#5 C:\path\to\project\vendor\cakephp\cakephp\src\View\View.php(363): Bake\View\BakeView->initialize()
#6 C:\path\to\project\vendor\cakephp\bake\src\Shell\Task\BakeTemplateTask.php(65): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), NULL, Array)
#7 C:\path\to\project\vendor\cakephp\bake\src\Shell\Task\BakeTemplateTask.php(86): Bake\Shell\Task\BakeTemplateTask->getView()
#8 C:\path\to\project\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(956): Bake\Shell\Task\BakeTemplateTask->generate('Model/table')
#9 C:\path\to\project\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(114): Bake\Shell\Task\ModelTask->bakeTable(Object(EventLog\Model\Table\MyModelTable), Array)
#10 C:\path\to\project\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(100): Bake\Shell\Task\ModelTask->bake('MyModel')
#11 C:\path\to\project\vendor\cakephp\cakephp\src\Console\Shell.php(507): Bake\Shell\Task\ModelTask->main('MyModel')
#12 C:\path\to\project\vendor\cakephp\cakephp\src\Console\Shell.php(500): Cake\Console\Shell->runCommand(Array, false, Array)
#13 C:\path\to\project\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#14 C:\path\to\project\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#15 C:\path\to\project\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#16 C:\path\to\project\bin\cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#17 {main}
```

**Comment by dereuromark** [comment]
Did you run conposer update? Are the dependencies downloaded as well?

**Comment by hraq** [comment]
Yes, composer update were too runned. Everything look like it's install ok, but not just work when bake.

**Comment by ADmad** [comment]
Please provide the output of 
`composer show -i`.

**Comment by hraq** [comment]
composer.json
```
 "require-dev": {
        ...
        "cakephp/bake": "^1.5",
        ...
  }
```

composer show -i
```
ajgl/breakpoint-twig-extension             0.3.1              Twig extension to set breakpoints
api/client                                 1.0.2
aptoma/twig-markdown                       2.0.0              Twig extension to work with Markdown content
asm89/twig-cache-extension                 1.3.2              Cache fragments of templates directly within Twig.
aura/intl                                  3.0.0              The Aura Intl package provides internationalization tools, specifically message translation.
cakephp/bake                               1.6.0              Bake plugin for CakePHP 3
cakephp/cakephp                            3.5.4              The CakePHP framework
cakephp/chronos                            1.1.4              A simple API extension for DateTime.
cakephp/debug_kit                          3.12.0             CakePHP Debug Kit
cakephp/migrations                         1.7.2              Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer                   1.1.0              A composer installer for CakePHP 3.0+ plugins.
codeguy/upload                             1.3.2              Handle file uploads with extensible validation and storage strategies
composer/ca-bundle                         1.1.0              Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer                          1.6.2              Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack everywhere.
composer/semver                            1.4.2              Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses                     1.2.0              SPDX licenses list and validation library.
container-interop/container-interop        1.2.0              Promoting the interoperability of container objects (DIC, SL, etc.)
deployer/deployer                          v4.3.2             Deployment Tool
dflydev/dot-access-data                    v1.1.0             Given a deep data structure, access data by dot notation.
dnoegel/php-xdg-base-dir                   0.1                implementation of xdg base directory specification for php
doctrine/instantiator                      1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
elboletaire/less-cake-plugin               v1.7.1             Less parser plugin for CakePHP
elfet/pure                                 v2.0.0             Pure PHP key-value storage
evenement/evenement                        v2.1.0             ├ëv├®nement is a very simple event dispatching library for PHP
friendsofcake/bootstrap-ui                 1.3.0              Twitter Bootstrap 3 support for CakePHP 3
friendsofcake/cakepdf                      3.3.1              CakePHP plugin for creating and/or rendering Pdfs, several Pdf engines supported.
friendsofcake/fixturize                    1.0.1              CakePHP Fixture classes to help increase productivity or performance
frontend/cakephp-js-translation            1.0.1              Cakephp js translations
guzzlehttp/guzzle                          6.3.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                        v1.3.1             Guzzle promises library
guzzlehttp/psr7                            1.4.2              PSR-7 message implementation that also provides common utility methods
havokinspiration/wrench                    2.1.0              Maintenance mode plugin for CakePHP 3.X
ifsnop/mysqldump-php                       v2.3.1             This is a php version of linux's mysqldump in terminal "$ mysqldump -u username -p..."
jakub-onderka/php-console-color            0.1
jakub-onderka/php-console-highlighter      v0.3.2
jasny/twig-extensions                      v1.2.0             A set of useful Twig filters
jdorn/sql-formatter                        v1.2.17            a PHP SQL highlighting library
jean85/pretty-package-versions             1.1                A wrapper for ocramius/pretty-package-versions to get pretty versions strings
justinrainbow/json-schema                  5.2.6              A library to validate a json schema.
lennaert/cakephp3-mandrill                 dev-master 60fe9b2 Mandrill Email Transport for CakePHP 3
lorenzo/audit-stash                        1.0.1              Flexible and rock solid audit log tracking plugin for cakephp
mobiledetect/mobiledetectlib               2.8.30             Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-Agent string combined with specific HTTP headers to detect the mobile environment.
moneyphp/money                             v3.1.1             PHP implementation of Fowler's Money pattern
monolog/monolog                            1.23.0             Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                          1.7.0              Create deep copies (clones) of your objects
nette/bootstrap                            v2.4.5             ­ƒà▒ Nette Bootstrap: the simple way to configure and bootstrap your Nette application.
nette/di                                   v2.4.10            ­ƒÆÄ Nette Dependency Injection Container: Flexible, compiled and full-featured DIC with perfectly usable autowiring and support for all new PHP 7.1 features.
nette/finder                               v2.4.1             Nette Finder: Files Searching
nette/neon                                 v2.4.2             Nette NEON: parser & generator for Nette Object Notation
nette/php-generator                        v3.0.1             ­ƒÉÿ Nette PHP Generator: generates neat PHP code for you. Supports new PHP 7.1 features.
nette/robot-loader                         v3.0.2             ­ƒìÇ Nette RobotLoader: high performance and comfortable autoloader that will search and autoload classes within your application.
nette/utils                                v2.4.8             ­ƒøá Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, validation, slug or strong password generating etc.
nikic/php-parser                           v3.1.4             A PHP parser written in PHP
ocramius/package-versions                  1.2.0              Composer plugin that provides efficient querying for installed package versions (no runtime IO)
oyejorge/less.php                          v1.7.0.14          PHP port of the Javascript version of LESS http://lesscss.org (Originally maintained by Josh Schmidt)
phar-io/manifest                           1.0.1              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                            1.0.1              Library for handling version information and constraints
phpdocumentor/reflection-common            1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock          4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver                0.4.0
phpseclib/phpseclib                        2.0.9              PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpspec/prophecy                           1.7.3              Highly opinionated mocking framework for PHP 5.3+
phpstan/phpdoc-parser                      0.2                PHPDoc parser with support for nullable, intersection and generic types
phpstan/phpstan                            0.9.2              PHPStan - PHP Static Analysis Tool
phpunit/php-code-coverage                  5.3.0              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                  1.4.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                  1.2.1              Simple template engine.
phpunit/php-timer                          1.0.9              Utility class for timing
phpunit/php-token-stream                   2.0.2              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                            6.5.5              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects               5.0.6              Mock Object library for PHPUnit
pimple/pimple                              v3.2.3             Pimple, a simple Dependency Injection Container
psr/cache                                  1.0.1              Common interface for caching libraries
psr/container                              1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                           1.0.1              Common interface for HTTP messages
psr/log                                    1.0.2              Common interface for logging libraries
psr/simple-cache                           1.0.0              Common interfaces for simple caching
psy/psysh                                  v0.8.17            An interactive shell for modern PHP.
ralouphie/mimey                            1.0.8              PHP package for converting file extensions to MIME types and vice versa.
react/cache                                v0.4.2             Async, Promise-based cache interface for ReactPHP
react/child-process                        v0.4.3             Library for executing child processes.
react/dns                                  v0.4.12            Async DNS resolver for ReactPHP
react/event-loop                           v0.4.3             Event loop abstraction layer that libraries can use for evented I/O.
react/http                                 v0.4.4             Library for building an evented http server.
react/http-client                          v0.4.17            Asynchronous HTTP client library.
react/promise                              v2.5.1             A lightweight implementation of CommonJS Promises/A for PHP
react/promise-timer                        v1.2.1             A trivial implementation of timeouts for Promises, built on top of ReactPHP.
react/react                                v0.4.2             Nuclear Reactor written in PHP.
react/socket                               v0.4.6             Async, streaming plaintext TCP/IP and secure TLS socket server for React PHP
react/socket-client                        v0.4.6             Async connector to open TCP/IP and SSL/TLS based connections.
react/stream                               v0.4.6             Basic readable and writable stream interfaces that support piping.
ringcentral/psr7                           1.2.2              PSR-7 message implementation
robmorgan/phinx                            v0.8.1             Phinx makes it ridiculously easy to manage the database migrations for your PHP app.
rquadling/phpunit-errorhandler             1.0.3              A simple trait to add to your PHPUnit test allowing you to track and test PHP errors, warnings and notices
sebastian/code-unit-reverse-lookup         1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                       2.1.2              Provides the functionality to compare PHP values for equality
sebastian/diff                             2.0.1              Diff implementation
sebastian/environment                      3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                         3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state                     2.0.0              Snapshotting of global state
sebastian/object-enumerator                3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector                 1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context                3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations              1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                          2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
seld/cli-prompt                            1.0.3              Allows you to prompt for user input on the command line, and optionally hide the characters they type
seld/jsonlint                              1.7.1              JSON Linter
seld/phar-utils                            1.0.1              PHAR file format utilities, for when PHP phars you up
slince/di                                  2.0.0              A flexible dependency injection container
squizlabs/php_codesniffer                  3.2.2              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
symfony/cache                              v3.4.4             Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                             v3.4.4             Symfony Config Component
symfony/console                            v3.4.4             Symfony Console Component
symfony/css-selector                       v3.4.4             Symfony CssSelector Component
symfony/debug                              v3.4.4             Symfony Debug Component
symfony/dom-crawler                        v3.4.4             Symfony DomCrawler Component
symfony/expression-language                v3.4.4             Symfony ExpressionLanguage Component
symfony/filesystem                         v3.4.4             Symfony Filesystem Component
symfony/finder                             v3.4.4             Symfony Finder Component
symfony/polyfill-apcu                      v1.6.0             Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-mbstring                  v1.6.0             Symfony polyfill for the Mbstring extension
symfony/process                            v3.4.4             Symfony Process Component
symfony/var-dumper                         v3.4.4             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                               v3.4.4             Symfony Yaml Component
theseer/tokenizer                          1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
twig/twig                                  v1.35.0            Twig, the flexible, fast, and secure template language for PHP
umpirsky/twig-php-function                 v0.1               Call (almost) any PHP function from your Twig templates.
vlucas/phpdotenv                           v2.4.0             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                           1.3.0              Assertions to validate method input/output with nice error messages.
wyrihaximus/twig-view                      4.3.1              Twig powered View for CakePHP3
zendframework/zend-diactoros               1.7.0              PSR HTTP Message implementations
```

**Comment by ADmad** [comment]
@WyriHaximus Any idea about this?

**Comment by WyriHaximus** [comment]
@ADmad will look into it :+1:

**Comment by WyriHaximus** [comment]
@ADmad @hraq found it, will work out a fix tonight

**Comment by WyriHaximus** [comment]
@hraq haven't been able to reproduce it locally but I came up with a (possible) fix. Could you run `composer require wyrihaximus/twig-view:dev-4.x-source-context` and try again?

**Comment by hraq** [comment]
Tried to instal on that way but just conflict with cakephp/bake requirements

**Comment by dereuromark** [comment]
You need to use aliasing then `... as x.y` etc. That will solve it.

**Comment by WyriHaximus** [comment]
@hraq you can test it with `composer require wyrihaximus/twig-view:dev-4.x-source-context as 4.2.2`. Didn't run unto any issues locally this morning so unless you still have issues I'de like to merge and tag the fix for this.

**Comment by WyriHaximus** [comment]
[`4.3.2`](https://github.com/WyriHaximus/TwigView/releases/tag/4.3.2) has been released to address this issue.

**Comment by makallio85** [comment]
I had the same issue and I was able to get rid of it by aliasing 4.3.2 as 4.3.0 but new error appears.
```
Exception: The possibility to register the same extension twice ("string") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead. in /var/www/html/vuokravalvonta/vendor/twig/twig/lib/Twig/Environment.php:944. in [/var/www/html/vuokravalvonta/vendor/twig/twig/lib/Twig/Environment.php, line 944]
2018-03-14 13:22:53 Error: [ErrorException] The possibility to register the same extension twice ("string") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead. in /var/www/html/vuokravalvonta/vendor/twig/twig/lib/Twig/Environment.php:944. in /var/www/html/vuokravalvonta/vendor/twig/twig/lib/Twig/Environment.php on line 944
Stack Trace:
#0 [internal function]: App\Console\ConsoleErrorHandler->handleError(16384, 'The possibility...', '/var/www/html/v...', 944, Array)
#1 /var/www/html/vuokravalvonta/vendor/twig/twig/lib/Twig/Environment.php(944): trigger_error('The possibility...', 16384)
#2 /var/www/html/vuokravalvonta/vendor/wyrihaximus/twig-view/src/Event/ExtensionsListener.php(71): Twig_Environment->addExtension(Object(WyriHaximus\TwigView\Lib\Twig\Extension\Strings))
#3 /var/www/html/vuokravalvonta/vendor/cakephp/cakephp/src/Event/EventManager.php(416): WyriHaximus\TwigView\Event\ExtensionsListener->construct(Object(WyriHaximus\TwigView\Event\ConstructEvent), Object(Bake\View\BakeView), Object(Twig_Environment))
#4 /var/www/html/vuokravalvonta/vendor/cakephp/cakephp/src/Event/EventManager.php(393): Cake\Event\EventManager->_callListener(Array, Object(WyriHaximus\TwigView\Event\ConstructEvent))
#5 /var/www/html/vuokravalvonta/vendor/wyrihaximus/twig-view/src/View/TwigView.php(69): Cake\Event\EventManager->dispatch(Object(WyriHaximus\TwigView\Event\ConstructEvent))
#6 /var/www/html/vuokravalvonta/vendor/cakephp/bake/src/View/BakeView.php(111): WyriHaximus\TwigView\View\TwigView->initialize()
#7 /var/www/html/vuokravalvonta/vendor/cakephp/cakephp/src/View/View.php(363): Bake\View\BakeView->initialize()
#8 /var/www/html/vuokravalvonta/vendor/cakephp/bake/src/Shell/Task/BakeTemplateTask.php(65): Cake\View\View->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), NULL, Array)
#9 /var/www/html/vuokravalvonta/vendor/cakephp/bake/src/Shell/Task/BakeTemplateTask.php(86): Bake\Shell\Task\BakeTemplateTask->getView()
#10 /var/www/html/vuokravalvonta/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(956): Bake\Shell\Task\BakeTemplateTask->generate('Model/table')
#11 /var/www/html/vuokravalvonta/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(114): Bake\Shell\Task\ModelTask->bakeTable(Object(Cake\ORM\Table), Array)
#12 /var/www/html/vuokravalvonta/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(100): Bake\Shell\Task\ModelTask->bake('LiabilitiesTemp...')
#13 /var/www/html/vuokravalvonta/vendor/cakephp/cakephp/src/Console/Shell.php(507): Bake\Shell\Task\ModelTask->main('LiabilitiesTemp...')
#14 /var/www/html/vuokravalvonta/vendor/cakephp/cakephp/src/Console/Shell.php(500): Cake\Console\Shell->runCommand(Array, false, Array)
#15 /var/www/html/vuokravalvonta/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#16 /var/www/html/vuokravalvonta/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#17 /var/www/html/vuokravalvonta/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#18 /var/www/html/vuokravalvonta/bin/cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#19 {main}
```

**Comment by WyriHaximus** [comment]
@makallio85 nice catch, just tagged 4.3.3 to counter that

**Comment by makallio85** [comment]
@WyriHaximus Seems to work for now. Thanks

**Comment by WyriHaximus** [comment]
@makallio85 glad to hear :+1:
