### ISSUE TITLE
bake model fails with "unknown as_array filter"

### ISSUE THREAD

**Issue by ava007** [cakephp/bake#533]
### Environment
CakePHP 4.0.0-alpha
PHP 7.3.2
PostgreSQL 11.2

### What I did
bin/cake bake model user

### Output
```
Exception: Unknown "as_array" filter. in [/usr/local/www .../vendor/cakephp/bake/templates/bake/Model/table.twig, line 49]
2019-04-23 18:42:47 Error: [Twig\Error\SyntaxError] Unknown "as_array" filter. in /usr/local/www.../vendor/cakephp/bake/templates/bake/Model/table.twig on line 49                                                                
Stack Trace:                                                                                                                 
#0 /usr/local/www.../vendor/twig/twig/src/ExpressionParser.php(491): Twig\ExpressionParser->getFilterNodeClass('as_array', 49)                                                                                                    
#1 /usr/local/www.../vendor/twig/twig/src/ExpressionParser.php(476): Twig\ExpressionParser->parseFilterExpressionRaw(Object(Twig\Node\Expression\NameExpression))                                                                 
#2 /usr/local/www.../vendor/twig/twig/src/ExpressionParser.php(334): Twig\ExpressionParser->parseFilterExpression(Object(Twig\Node\Expression\NameExpression))                                                                    
#3 /usr/local/www.../vendor/twig/twig/src/ExpressionParser.php(226): Twig\ExpressionParser->parsePostfixExpression(Object(Twig\Node\Expression\NameExpression))                                                                   
#4 /usr/local/www.../vendor/twig/twig/src/ExpressionParser.php(112): Twig\ExpressionParser->parsePrimaryExpression()                                                                                                              
#5 /usr/local/www.../vendor/twig/twig/src/ExpressionParser.php(65): Twig\ExpressionParser->getPrimary()                                                                                                                           
#6 /usr/local/www.../vendor/twig/twig/src/Parser.php(142): Twig\ExpressionParser->parseExpression()  
#7 /usr/local/www.../vendor/twig/twig/src/TokenParser/IfTokenParser.php(48): Twig\Parser->subparse(Array)                                                                                                                         
#8 /usr/local/www.../vendor/twig/twig/src/Parser.php(185): Twig\TokenParser\IfTokenParser->parse(Object(Twig\Token))                                                                                                              
#9 /usr/local/www.../vendor/twig/twig/src/TokenParser/IfTokenParser.php(39): Twig\Parser->subparse(Array)                                                                                                                         
#10 /usr/local/www.../vendor/twig/twig/src/Parser.php(185): Twig\TokenParser\IfTokenParser->parse(Object(Twig\Token))                                                                                                             
#11 /usr/local/www.../vendor/twig/twig/src/Parser.php(98): Twig\Parser->subparse(NULL, false)        
#12 /usr/local/www.../vendor/twig/twig/src/Environment.php(563): Twig\Parser->parse(Object(Twig\TokenStream))                                                                                                                     
#13 /usr/local/www.../vendor/twig/twig/src/Environment.php(595): Twig\Environment->parse(Object(Twig\TokenStream))                                                                                                                
#14 /usr/local/www.../vendor/twig/twig/src/Environment.php(408): Twig\Environment->compileSource(Object(Twig\Source))                                                                                                             
#15 /usr/local/www.../vendor/twig/twig/src/Environment.php(381): Twig\Environment->loadClass('__TwigTemplate_...', '/usr/local/www/...', NULL)                                                                                    
#16 /usr/local/www.../vendor/wyrihaximus/twig-view/src/View/TwigView.php(191): Twig\Environment->loadTemplate('/usr/local/www/...')                                                                                               
#17 /usr/local/www.../vendor/cakephp/bake/src/View/BakeView.php(109): WyriHaximus\TwigView\View\TwigView->_render('/usr/local/www/...')                                                                                           
#18 /usr/local/www.../vendor/cakephp/bake/src/Utility/TemplateRenderer.php(100): Bake\View\BakeView->render('Model/table')                                                                                                        
#19 /usr/local/www.../vendor/cakephp/bake/src/Command/ModelCommand.php(1006): Bake\Utility\TemplateRenderer->generate('Model/table')                                                                                              
#20 /usr/local/www.../vendor/cakephp/bake/src/Command/ModelCommand.php(97): Bake\Command\ModelCommand->bakeTable(Object(Cake\ORM\Table), Array, Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))                   
#21 /usr/local/www.../vendor/cakephp/bake/src/Command/ModelCommand.php(79): Bake\Command\ModelCommand->bake('User', Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))                                               
#22 /usr/local/www.../vendor/cakephp/cakephp/src/Console/Command.php(178): Bake\Command\ModelCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))                                                     
#23 /usr/local/www.../vendor/cakephp/cakephp/src/Console/CommandRunner.php(322): Cake\Console\Command->run(Array, Object(Cake\Console\ConsoleIo))                                                                                 
#24 /usr/local/www.../vendor/cakephp/cakephp/src/Console/CommandRunner.php(161): Cake\Console\CommandRunner->runCommand(Object(Bake\Command\ModelCommand), Array, Object(Cake\Console\ConsoleIo))                                 
#25 /usr/local/www.../bin/cake.php(12): Cake\Console\CommandRunner->run(Array) 


PostgreSQL (11.2)

 \d user
                                        Table "user"
   Column   |           Type           | Collation | Nullable |                 Default                 
------------+--------------------------+-----------+----------+-----------------------------------------
 id         | character(36)            |           | not null | 
 nick       | character varying(24)    |           | not null | 
 email      | character varying(255)   |           | not null | 
 lang       | character(2)             |           |          | 'en'::bpchar
 last_login | timestamp with time zone |           |          | 
 created    | timestamp with time zone |           |          | ('now'::text)::timestamp with time zone
 modified   | timestamp with time zone |           |          | ('now'::text)::timestamp with time zone
Indexes:
    "user_pkey" PRIMARY KEY, btree (id)
    "user_email" UNIQUE, btree (email)
    "user_nick" UNIQUE, btree (nick)
Referenced by:
    TABLE "entry" CONSTRAINT "entry_user_fk" FOREIGN KEY (user_id) REFERENCES "user"(id)


seems to be related to
#391

**Comment by saeideng** [comment]
`bin/cake bake model users` works for me 
on latest bake 4.x commit

cake 4.x
bake 4.x
mysql

**Comment by ava007** [comment]
I did a fresh install and have still the same problem.

The following versions are installed:
cakephp/cakephp (4.x-dev 2d5742c)
cakephp/bake (4.x-dev 1837a72)
twig/twig (### v2.8.1)
wyrihaximus/twig-view (dev-master dba3d80)

**Comment by saeideng** [comment]
I installed it just now again (fresh install)
```
composer create-project cakephp/app=4.0.0-alpha1 project-name
//config DB name in `config/app.php`
bin/cake bake model users
```
works for me 



add `$this->addPlugin('WyriHaximus/TwigView');` into `src/Application.php` and test again 

 you are  using `PHP 7.3.2` / `PostgreSQL 11.2`
but I  php 7.2 / mysql 
I can not see other difference 

```
composer show

aptoma/twig-markdown                  3.1.0              Twig extension to work with Markdown content
asm89/twig-cache-extension            1.3.2              Cache fragments of templates directly within Twig.
aura/intl                             3.0.0              The Aura Intl package provides internationalization tools, specifically message translation.
cakephp/bake                          4.x-dev 1837a72    Bake plugin for CakePHP
cakephp/cakephp                       4.x-dev 2d5742c    The CakePHP framework
cakephp/cakephp-codesniffer           dev-next 3227280   CakePHP CodeSniffer Standards
cakephp/chronos                       2.x-dev 6c7b974    A simple API extension for DateTime.
cakephp/debug_kit                     4.x-dev 50b70f9    CakePHP Debug Kit
cakephp/plugin-installer              1.1.0              A composer installer for CakePHP 3.0+ plugins.
composer/ca-bundle                    1.1.4              Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer                     1.8.5              Composer helps you declare, manage and install dependencies of PHP projects, ensuring you ha...
composer/semver                       1.5.0              Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses                1.5.1              SPDX licenses list and validation library.
composer/xdebug-handler               1.3.2              Restarts a process without xdebug.
dnoegel/php-xdg-base-dir              0.1                implementation of xdg base directory specification for php
doctrine/instantiator                 1.2.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
jakub-onderka/php-console-color       v0.2              
jakub-onderka/php-console-highlighter v0.4               Highlight PHP code in terminal
jasny/twig-extensions                 v1.2.0             A set of useful Twig filters
jdorn/sql-formatter                   v1.2.17            a PHP SQL highlighting library
josegonzalez/dotenv                   3.2.0              dotenv file parsing for PHP
justinrainbow/json-schema             5.2.8              A library to validate a json schema.
m1/env                                2.1.2              Env is a lightweight library bringing .env file parser compatibility to PHP. In short - it e...
mobiledetect/mobiledetectlib          2.8.33             Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-Agen...
myclabs/deep-copy                     1.9.1              Create deep copies (clones) of your objects
nikic/php-parser                      v4.2.1             A PHP parser written in PHP
phar-io/manifest                      1.0.3              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       2.0.1              Library for handling version information and constraints
phpdocumentor/reflection-common       1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwis...
phpdocumentor/type-resolver           0.4.0             
phpspec/prophecy                      1.8.0              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             6.1.4              Library that provides collection, processing, and rendering functionality for PHP code cover...
phpunit/php-file-iterator             2.0.2              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     2.1.1              Utility class for timing
phpunit/php-token-stream              3.0.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       7.5.9              The PHP Unit Testing framework.
psr/http-client                       1.0.0              Common interface for HTTP clients
psr/http-factory                      1.0.0              Common interfaces for PSR-7 HTTP message factories
psr/http-message                      1.0.1              Common interface for HTTP messages
psr/http-server-handler               1.0.1              Common interface for HTTP server-side request handler
psr/http-server-middleware            1.0.1              Common interface for HTTP server-side middleware
psr/log                               1.1.0              Common interface for logging libraries
psr/simple-cache                      1.0.1              Common interfaces for simple caching
psy/psysh                             v0.9.9             An interactive shell for modern PHP.
sebastian/code-unit-reverse-lookup    1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                  3.0.2              Provides the functionality to compare PHP values for equality
sebastian/diff                        3.0.2              Diff implementation
sebastian/environment                 4.2.1              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state                2.0.0              Snapshotting of global state
sebastian/object-enumerator           3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector            1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context           3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations         2.0.1              Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                         1.7.1              JSON Linter
seld/phar-utils                       1.0.1              PHAR file format utilities, for when PHP phars you up
slevomat/coding-standard              4.8.7              Slevomat Coding Standard for PHP_CodeSniffer complements Consistence Coding Standard by prov...
squizlabs/php_codesniffer             3.4.2              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined ...
symfony/console                       v4.2.7             Symfony Console Component
symfony/contracts                     v1.0.2             A set of abstractions extracted out of the Symfony components
symfony/filesystem                    v4.2.7             Symfony Filesystem Component
symfony/finder                        v4.2.7             Symfony Finder Component
symfony/polyfill-ctype                v1.11.0            Symfony polyfill for ctype functions
symfony/polyfill-mbstring             v1.11.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                v1.11.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                       v4.2.7             Symfony Process Component
symfony/var-dumper                    v4.2.7             Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                     1.1.2              A small library for converting tokenized PHP source code into XML and potentially other formats
twig/twig                             v2.8.1             Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                      1.4.0              Assertions to validate method input/output with nice error messages.
wyrihaximus/twig-view                 dev-master 487f165 Twig powered View for CakePHP
zendframework/zend-diactoros          2.1.1              PSR HTTP Message implementations
zendframework/zend-httphandlerrunner  1.1.0              Execute PSR-15 RequestHandlerInterface instances and emit responses they generate.
```

**Comment by ava007** [comment]
It works not after updating to the latest version.  Additional loadplugin was not required.

Thanks to  @saeideng

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Removing cakephp/bake (4.x-dev 1837a72)
  - Installing cakephp/bake (4.x-dev c4b8327): Cloning c4b83277da from cache
  - Removing wyrihaximus/twig-view (dev-master dba3d80)
  - Installing wyrihaximus/twig-view (dev-master 487f165): Cloning 487f165cbd from cache
Writing lock file
Generating autoload files
