### ISSUE TITLE
Bake model:  Cache key `myapp_cake_model_default_"user"` contains invalid characters

### ISSUE THREAD

**Issue by ava007** [cakephp/bake#535]
### Environment:
CakePHP 4.x
Bake 4.x
PHP 7.3.2
PostgreSQL 11.2

### What I did:
bin/cake bake model Entry

### Result (not as expected):

```
Exception: Cache key `myapp_cake_model_default_"user"` contains invalid characters. You cannot use /, \, <, >, ?, :, |, *, or " in cache keys. in [/usr/local/.../lfcakephp4/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 431]
2019-04-26 18:12:58 Error: [Cake\Cache\InvalidArgumentException] Cache key `myapp_cake_model_default_"user"` contains invalid characters. You cannot use /, \, <, >, ?, :, |, *, or " in cache keys. in /usr/local/.../lfcakephp4/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php on line 431      
Stack Trace:                                                                                                                                                 
#0 /usr/local/www/.../vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php(174): Cake\Cache\Engine\FileEngine->_key('myapp_cake_mode...')                                                                                                                                                        
#1 /usr/local/www/.../lfcakephp4/vendor/cakephp/cakephp/src/Cache/Cache.php(327): Cake\Cache\Engine\FileEngine->get('default_"user"')            
#2 /usr/local/www/.../lfcakephp4/vendor/cakephp/cakephp/src/Database/Schema/CachedCollection.php(79): Cake\Cache\Cache::read('default_"user"', '_cake_model_')                                                                                                                                                
#3 /usr/local/www/.../lfcakephp4/vendor/cakephp/cakephp/src/ORM/Table.php(487): Cake\Database\Schema\CachedCollection->describe('"user"')        
#4 /usr/local/www/.../lfcakephp4/vendor/cakephp/bake/src/Command/ModelCommand.php(913): Cake\ORM\Table->getSchema()                              
#5 /usr/local/www/.../lfcakephp4/vendor/cakephp/bake/src/Command/ModelCommand.php(890): Bake\Command\ModelCommand->getCounterCache(Object(Cake\ORM\Table))                                                                                                                                                    
#6 /usr/local/www/.../lfcakephp4/vendor/cakephp/bake/src/Command/ModelCommand.php(131): Bake\Command\ModelCommand->getBehaviors(Object(Cake\ORM\Table))                                                                                                                                                       
#7 /usr/local/www/.../lfcakephp4/vendor/cakephp/bake/src/Command/ModelCommand.php(97): Bake\Command\ModelCommand->getTableContext(Object(Cake\ORM\Table), 'entry', 'Entry', Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))                                                                   
#8 /usr/local/www/.../lfcakephp4/vendor/cakephp/bake/src/Command/ModelCommand.php(79): Bake\Command\ModelCommand->bake('Entry', Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))                                                                                                               
#9 /usr/local/www/..../lfcakephp4/vendor/cakephp/cakephp/src/Console/Command.php(178): Bake\Command\ModelCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))                                                                                                                      
#10 /usr/local/www/.../lfcakephp4/vendor/cakephp/cakephp/src/Console/CommandRunner.php(323): Cake\Console\Command->run(Array, Object(Cake\Console\ConsoleIo))                                                                                                                                                 
#11 /usr/local/www/.../lfcakephp4/vendor/cakephp/cakephp/src/Console/CommandRunner.php(161): Cake\Console\CommandRunner->runCommand(Object(Bake\Command\ModelCommand), Array, Object(Cake\Console\ConsoleIo))                                                                                                 
#12 /usr/local/www/.../lfcakephp4/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)                                                       
#13 {main}                                                                                                          
```

**Comment by ava007** [comment]
### Database Table:

\d entry
                                      Table "entry"
  Column  |           Type           | Collation | Nullable |                 Default                 
----------+--------------------------+-----------+----------+-----------------------------------------
 id       | character(36)            |           | not null | 
 user_id  | character(36)            |           | not null | 
 created  | timestamp with time zone |           |          | ('now'::text)::timestamp with time zone
 modified | timestamp with time zone |           |          | ('now'::text)::timestamp with time zone
 etyp     | character(1)             |           | not null | 
 etitle   | character varying(80)    |           | not null | 
 etags    | character varying(255)   |           |          | 
 eurl     | character varying(255)   |           |          | 
 etext    | character varying(12000) |           |          | 
 etag     | jsonb                    |           |          | 
Indexes:
    "entry_pkey" PRIMARY KEY, btree (id)
    "entry_eurl" UNIQUE, btree (user_id, eurl, etags) WHERE eurl IS NOT NULL
    "entry_tags_index" gin (etag)
    "entry_user" btree (user_id)
Check constraints:
    "entry_etyp_check" CHECK (etyp = ANY (ARRAY['l'::bpchar, 'i'::bpchar, 'v'::bpchar, 't'::bpchar, 'd'::bpchar]))
Foreign-key constraints:
    "entry_user_fk" FOREIGN KEY (user_id) REFERENCES "user"(id)


### Workround: 
file vendor/cakephp/bake/src/Command/ModelCommand.php

 public function findTableReferencedBy(\Cake\Database\Schema\TableSchema $schema, string $keyField): ?string

changed (old):
    return $constraintInfo['references'][0];
new:
 return str_replace('"','',$constraintInfo['references'][0]);

Should I open as PR?

**Comment by markstory** [comment]
Thanks for filing this. Your issue seems like an issue with the schema reflection features in CakePHP's database layer and less of a problem with bake. Ideally the postgres schema reflection would strip `"` off of referenced table names.

**Comment by ava007** [comment]
I've check to PostgreSQL catalog, which shows the following:

select confrelid::regclass from pg_constraint;
 do_user
 "user"

Therefore I will correct the SQL-DDL instead of changing the code.

thanks
