### ISSUE TITLE
4.x - Template help missing?

### ISSUE THREAD

**Issue by davidyell** [cakephp/bake#547]
## What did you do?
```bash
~/Sites/CakePHP4 $ bin/cake bake template --help
Exception: strlen() expects parameter 1 to be string, int given in [/Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php, line 175]
2019-05-19 11:14:16 Error: [TypeError] strlen() expects parameter 1 to be string, int given in /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php on line 175
Stack Trace:
#0 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php(175): strlen(0)
#1 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/HelpFormatter.php(173): Cake\Console\ConsoleInputOption->usage()
#2 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/HelpFormatter.php(97): Cake\Console\HelpFormatter->_generateUsage()
#3 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/ConsoleOptionParser.php(737): Cake\Console\HelpFormatter->text(72)
#4 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/Command.php(197): Cake\Console\ConsoleOptionParser->help(NULL, 'text')
#5 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/Command.php(173): Cake\Console\Command->displayHelp(Object(Cake\Console\ConsoleOptionParser), Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#6 /Users/davidyell/Sites/CakePHP4/vendor/cakephp/cakephp/src/Console/CommandRunner.php(161): Cake\Console\Command->run(Array, Object(Cake\Console\ConsoleIo))
#7 /Users/davidyell/Sites/CakePHP4/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#8 {main}
```

## What happened?
An exception was thrown

## What did you expect to happen?
I was hoping to see the option switches for the command as I was trying to add my own bake theme.

**Comment by saeideng** [comment]
fixed here https://github.com/cakephp/cakephp/pull/13226
