### ISSUE TITLE
Tests not running on plugins containing bootstrap file

### ISSUE THREAD

**Issue by rogerpro** [cakephp/bake#559]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.8
* Platform and Target: Ubuntu on Docker.

### What you did
* Installed an app with `composer create-project --prefer-dist cakephp/app my_app_name`
* Baked a plugin with `bin/cake bake plugin ContactManager`
* `bin/cake bake test Controller AppController`
* `cd plugins/ContactManager/`
* `composer install`
* `touch config/bootstrap.php`
* `vendor/bin/phpunit`

### What happened
Got an error:
```
PHP Fatal error:  Uncaught Error: Call to undefined function Cake\TestSuite\Fixture\loadPHPUnitAliases() in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php:17
Stack trace:
#0 /home/total/mnt/my_app_name/plugins/ContactManager/vendor/composer/ClassLoader.php(444): include()
#1 /home/total/mnt/my_app_name/plugins/ContactManager/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/total/mnt...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Cake\\TestSuite\\...')
#3 /home/total/mnt/my_app_name/plugins/ContactManager/vendor/phpunit/phpunit/src/Util/Xml.php(238): spl_autoload_call('Cake\\TestSuite\\...')
#4 /home/total/mnt/my_app_name/plugins/ContactManager/vendor/phpunit/phpunit/src/Util/Configuration.php(356): PHPUnit\Util\Xml::xmlToVariable(Object(DOMElement))
#5 /home/total/mnt/my_app_name/plugins/ContactManager/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(923): PHPUnit\Util\Configuration->getListenerConfiguration()
 in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php on line 17
```

### What you expected to happen
Usual PHPUnit process as:
```
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.



Time: 243 ms, Memory: 4.00MB

No tests executed!
```

**Comment by markstory** [comment]
Moved to bake as it sounds like the generated plugin is missing code to ensure that `loadPHPUnitAliases()` has been loaded before tests run.

**Comment by markstory** [comment]
Pull request open now.

**Comment by rogerpro** [comment]
Hi Mark,

We still get the warnings when we follow the "What you did" process except `touch config/bootstrap.php`:
```
total@1be122b3be79:~/mnt/my_app_name/plugins/ContactManager$ rm config/bootstrap.php
total@1be122b3be79:~/mnt/my_app_name/plugins/ContactManager$ vendor/bin/phpunit
PHP Notice:  Constant SECOND already defined in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/basics.php on line 21
PHP Notice:  Constant MINUTE already defined in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/basics.php on line 22
PHP Notice:  Constant HOUR already defined in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/basics.php on line 23
PHP Notice:  Constant DAY already defined in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/basics.php on line 24
PHP Notice:  Constant WEEK already defined in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/basics.php on line 25
PHP Notice:  Constant MONTH already defined in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/basics.php on line 26
PHP Notice:  Constant YEAR already defined in /home/total/mnt/my_app_name/plugins/ContactManager/vendor/cakephp/cakephp/src/basics.php on line 27
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.



Time: 288 ms, Memory: 4.00MB

No tests executed!
```

This happens using `"cakephp/bake": "dev-master",`. It looks like `/vendor/cakephp/cakephp/src/basics.php` is called twice.

**Comment by markstory** [comment]
@rogerpro Ok. I'll take another look.

**Comment by ADmad** [comment]
For reference this is the bootstrap file I have been using in my plugins and don't rememeber having any issues: https://github.com/ADmad/cakephp-social-auth/blob/master/tests/bootstrap.php  (The last line can be ignored).

**Comment by rogerpro** [comment]
@ADmad did you ran your plugin's tests as standalone, or installed in an app?

**Comment by ADmad** [comment]
Standalone

**Comment by rogerpro** [comment]
Everything working well with CakePHP 3.8.0 & Bake 1.11.0. Thanks.
