### ISSUE TITLE
When baking (bin\cake bake all) with "--connection" parameter it throws error when it comes to the Templates (Views)

### ISSUE THREAD

**Issue by icaroscherma** [cakephp/bake#63]
When I separated an App in two databases, if I try to bake something from a db other than the default, it is supposed to run smoothly if I use `--connection CONNECTION_NAME`, but it doesn't, when it reaches in the Templates (Views), it says that:

```
Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cakeapp_db.timelines' doesn't exist in [C:\cakeapp\vendor\cakephp\cakephp\src\Database\Schema\Collection.php, line 130]

2015-03-31 18:34:07 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cakeapp_db.timelines' doesn't exist
Stack Trace:
#0 C:\cakeapp\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(96): Cake\Database\Schema\Collection->_reflect('Column', 'timelines', Array, Object(Cake\Database\Schema\Table))
#1 C:\cakeapp\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(65): Cake\Database\Schema\Collection->describe('timelines', Array)

#2 C:\cakeapp\vendor\cakephp\cakephp\src\ORM\Table.php(422): Cake\Database\Schema\CachedCollection->describe('timelines')

#3 C:\cakeapp\vendor\cakephp\bake\src\Shell\Task\TemplateTask.php(273): Cake\ORM\Table->schema()

#4 C:\cakeapp\vendor\cakephp\bake\src\Shell\Task\TemplateTask.php(139): Bake\Shell\Task\TemplateTask->_loadController()

#5 C:\cakeapp\vendor\cakephp\bake\src\Shell\BakeShell.php(243): Bake\Shell\Task\TemplateTask->main('Timelines')

#6 [internal function]: Bake\Shell\BakeShell->all('timelines')

#7 C:\cakeapp\vendor\cakephp\cakephp\src\Console\Shell.php(376): call_user_func_array(Array, Array)

#8 C:\cakeapp\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(200): Cake\Console\Shell->runCommand(Array, true)

#9 C:\cakeapp\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(171): Cake\Console\ShellDispatcher->_dispatch()

#10 C:\cakeapp\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(122): Cake\Console\ShellDispatcher->dispatch()

#11 C:\cakeapp\bin\cake.php(20): Cake\Console\ShellDispatcher::run(Array)

#12 {main}
```

Take for instance `C:\cakeapp` as the base directory, `cakeapp_db` as the database name from the default database, and `timelines` as the name of the Object that I'm trying to bake.

**Comment by markstory** [comment]
What does your timelines model look like?

**Comment by icaroscherma** [comment]
This is the point, I only made the database table in MySQL then I tried to `cake bake all`, so it is supposed to generate everything (controller, model, view with basic crud).

When it first generates, the code is like:
```
<?php
namespace App\Model\Table;

use App\Model\Entity\Timeline;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Timelines Model
 */
class TimelinesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        $this->table('timelines');
        $this->displayField('title');
        $this->primaryKey('id');
        $this->addBehavior('Timestamp');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->add('id', 'valid', ['rule' => 'numeric'])
            ->allowEmpty('id', 'create')
            ->requirePresence('date', 'create')
            ->notEmpty('date')
            ->requirePresence('title', 'create')
            ->notEmpty('title')
            ->requirePresence('content', 'create')
            ->notEmpty('content');

        return $validator;
    }
}
```

then I added the code (`website` is the secondary database):
```
    public static function defaultConnectionName()
    {
        return 'website';
    }
```

and after re-run the same command (but telling not to overwrite the `TimelinesTable.php`), then it can bake the Templates/Views.

**Comment by icaroscherma** [comment]
I don't know if this helps, but I think that in the file `bake\src\Template\Bake\Model\table.ctp` is missing a piece of code like this:

```
<% if (!_DB_CONNECTION_IS_NOT_THE_DEFAULT): %>

    /**
     * Returns the database name to be used as a connection for this table.
     *
     * @return String
     */
    public static function defaultConnectionName()
    {
        return __NAME_OF_THE_USED_CONNECTION__;
    }
<% endif; %>
```
Where `_DB_CONNECTION_IS_NOT_THE_DEFAULT` and `__NAME_OF_THE_USED_CONNECTION__` needs to be changed to match the proper variables.

**Comment by icaroscherma** [comment]
I don't know if I have permission to edit/push modifications, nor if this is the proper solution but I figured out a way around, you have to modify 2 files:

`bake\src\Shell\Task\ModelTask.php`
```
Inside the function bake, create one more variable and set it to $this->connection (next line).
        $connection = $this->connection;

Still in the function bake, add the created variable to the array data (next lines):
    $data = compact(
        'associations',
        'primaryKey',
        'displayField',
        'table',
        'fields',
        'validation',
        'rulesChecker',
        'behaviors',
        'connection'
    );

Inside the function bakeTable, add one more setting to the array data (next line):
    'connection' => $this->connection,
```


`bake\src\Template\Bake\Model\table.ctp`: Prepend this content before the last line.
```
<% if ($connection != 'default'): %>

    /**
     * Returns the database name to be used as a connection for this table.
     *
     * @return String
     */
    public static function defaultConnectionName()
    {
        return '<%= $connection %>';
    }
<% endif; %>
```

I hope this solution helps. =x

**Comment by markstory** [comment]
That does help @icaroscherma. I had a hunch that the models were not being generated correctly, which has been confirmed. I'll put up a pull request to fix that tonight.

**Comment by markstory** [comment]
Pull request up now.
